In [ ]:
import numpy as np

In [ ]:
data=np.random.randn(2,5)
data

array([[ 1.96001235,  0.35452287,  1.72444722, -1.62463172, -0.55839996],
       [ 0.57175648,  0.2660137 , -2.59801644,  1.12864764, -1.14852609]])

In [ ]:
data*10

array([[ 19.60012354,   3.54522867,  17.2444722 , -16.24631724,
         -5.58399962],
       [  5.71756481,   2.66013703, -25.98016438,  11.28647636,
        -11.48526089]])

In [ ]:
data.shape

(2, 5)

In [ ]:
data.dtype

dtype('float64')

In [ ]:
data.ndim

2

***different ways to create ndarray***

In [ ]:
python_list=[3,2,0.5,7,9,10,"abc"]
array=np.array(python_list)
array

array(['3', '2', '0.5', '7', '9', '10', 'abc'], dtype='<U32')

In [ ]:
data=np.random.seed(3)
data
print(data)

None

In [ ]:
type(array)

numpy.ndarray

In [ ]:
file_name="sample.text"
file=open(file_name,"r")
txt=file.read()

FileNotFoundError: [Errno 2] No such file or directory: 'sample.text'

In [ ]:
from google.colab import files
uploaded=files.upload()

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_xlsx('/Excel Project.xlsx')

AttributeError: module 'pandas' has no attribute 'read_xlsx'

In [ ]:
df.head()

In [ ]:
from google.colab import files
uploaded=files.upload()

In [ ]:
import pandas as pd

In [ ]:
import io
df=pd.read_excel(io.BytesIO(uploaded['Coffee Shop Sales.xlsx']))

In [ ]:
df

NameError: name 'df' is not defined

In [ ]:
df=df.drop_duplicates()
df

In [ ]:
df=df.drop(columns='transaction_time')
df

In [ ]:
df=df['product_detail']=df['product_detail'].str.replace('Lg','Large')
df['product_detail']=df['product_detail'].str.replace('Rg','Regular')
df

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/archive (2).zip')
df.head

In [ ]:
from google.colab import files
uploaded=files.upload()

In [ ]:
import pandas as pd

In [ ]:
pd=pd.read_csv('/Temu Data set.zip')

NameError: name 'pd' is not defined

In [ ]:
df.head

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df

NameError: name 'df' is not defined

In [ ]:
df.tail(10)

In [ ]:
people_dict={

                "first_name":["hira", "zahwa"],
                 "last_name":["zahra","yousaf"]
}
print(people_dict)
people_dict["first_name"]

{'first_name': ['hira', 'zahwa'], 'last_name': ['zahra', 'yousaf']}

['hira', 'zahwa']

In [ ]:
import pandas as pd

In [ ]:
df=pd.DataFrame(people_dict)
df

  first_name last_name
0       hira     zahra
1      zahwa    yousaf

In [ ]:
df['first_name']

0     hira
1    zahwa
Name: first_name, dtype: object

In [ ]:
df.columns

Index(['first_name', 'last_name'], dtype='object')

In [ ]:
df.iloc[[0,1]]

  first_name last_name
0       hira     zahra
1      zahwa    yousaf

In [ ]:
df.iloc[0,1]

'zahra'

In [ ]:
df.loc[0,:]

first_name     hira
last_name     zahra
Name: 0, dtype: object

In [ ]:
studentD={

                "first_name":["hira", "zahwa","Ali"],
                 "last_name":["zahra","yousaf","sara"],
                "city":["lahore","karachi",'Isl'],
                "address":["12A","H66B","KDa12"]
}
print(studentD)

{'first_name': ['hira', 'zahwa', 'Ali'], 'last_name': ['zahra', 'yousaf', 'sara'], 'city': ['lahore', 'karachi', 'Isl'], 'address': ['12A', 'H66B', 'KDa12']}

In [ ]:
import pandas as pd
df=pd.DataFrame(studentD)

In [ ]:
df

  first_name last_name     city address
0       hira     zahra   lahore     12A
1      zahwa    yousaf  karachi    H66B
2        Ali      sara      Isl   KDa12

In [ ]:
df.iloc[0:1],[0]

(  first_name last_name    city address
 0       hira     zahra  lahore     12A,
 [0])

In [ ]:
df.loc[1],["first_name"]

(first_name      zahwa
 last_name      yousaf
 city          karachi
 address          H66B
 Name: 1, dtype: object,
 ['first_name'])

In [ ]:
df.loc[0:3,'city':'address']

      city address
0   lahore     12A
1  karachi    H66B
2      Isl   KDa12

In [ ]:
df.iloc[[0,1],0:2]

  first_name last_name
0       hira     zahra
1      zahwa    yousaf

In [ ]:
df.iloc[0:3,[1,2,3]]

  last_name     city address
0     zahra   lahore     12A
1    yousaf  karachi    H66B
2      sara      Isl   KDa12

In [ ]:
df['phone_no']=[235478,245872,254741]

In [ ]:
df

   Rank customer purchaser  medium
11   11       c1         y      20
12   12       c2         n      40
13   13       c3         n      50

In [ ]:
df.set_index('city',inplace=True)

In [ ]:
df

        first_name last_name address  phone_no
city
lahore        hira     zahra     12A    235478
karachi      zahwa    yousaf    H66B    245872
Isl            Ali      sara   KDa12    254741

In [ ]:
df.index

Index(['lahore', 'karachi', 'Isl'], dtype='object', name='city')

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df

      city first_name last_name address  phone_no
0   lahore       hira     zahra     12A    235478
1  karachi      zahwa    yousaf    H66B    245872
2      Isl        Ali      sara   KDa12    254741

In [ ]:
new_order = ["first_name","last_name","city"	,"address",	"phone_no"]
df = df[new_order]

In [ ]:
df

  first_name last_name     city address  phone_no
0       hira     zahra   lahore     12A    235478
1      zahwa    yousaf  karachi    H66B    245872
2        Ali      sara      Isl   KDa12    254741

In [ ]:
display(df)

  first_name last_name     city address  phone_no
0       hira     zahra   lahore     12A    235478
1      zahwa    yousaf  karachi    H66B    245872
2        Ali      sara      Isl   KDa12    254741

In [ ]:
pd.Series('city')

0    city
dtype: object

In [ ]:
df=pd.DataFrame(np.random.randn(5,4),index='A B C D E'.split(),columns="x y z w ".split())

In [ ]:
list(df.columns)

['x', 'y', 'z', 'w']

In [ ]:
df

          x         y         z         w
A  1.788628  0.436510  0.096497 -1.863493
B -0.277388 -0.354759 -0.082741 -0.627001
C -0.043818 -0.477218 -1.313865  0.884622
D  0.881318  1.709573  0.050034 -0.404677
E -0.545360 -1.546477  0.982367 -1.101068

In [ ]:
df.loc[['B'],"x"]

B   -0.277388
Name: x, dtype: float64

In [ ]:
df.iloc[1,0]

np.float64(-0.27738820251439905)

**list_style vs dict_style**

In [ ]:
# Nested list style practice is list, and we use seperate column to give a heading to columns
parct=[ [1,"pak","south asia",2.50,],[2,"sharja","middle_east",1.0,],[3,"missisaga","Canada",5.50,]]
columns=['s.ro','continent','city_n','pop']

In [ ]:
df=pd.DataFrame(data=parct,columns=columns)
print(df)

   s.ro  continent       city_n  pop
0     1        pak   south asia  2.5
1     2     sharja  middle_east  1.0
2     3  missisaga       Canada  5.5

In [ ]:
#dictionary style is used with index, no column header needed
consumers={  "Rank":["11", "12", "13"],
    "customer":["c1", "c2", "c3"],
           "purchaser":['y','n','n'],
           "medium":[20,40,50]
          }


df=pd.DataFrame(data=consumers,index=consumers['Rank'])
print(df)

   Rank customer purchaser  medium
11   11       c1         y      20
12   12       c2         n      40
13   13       c3         n      50

                                               **Series **

In [ ]:
import pandas as pd

In [ ]:
s=pd.Series(['dog','human','lizard'],index=['mamal','mamal','reptiles'])
print(s[2])

lizard

/tmp/ipython-input-1620080142.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[2])

In [ ]:
values={'mamal':'dog','mamal1':"human","reptile":'lizard'}
s=pd.Series(values)
print(s)

mamal         dog
mamal1      human
reptile    lizard
dtype: object

In [ ]:
import numpy as np      # we can create a series in numpy as np using (arange) attribute
a=np.arange(10)
s=pd.Series(a)
print(s)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [ ]:
s=pd.Series("a",index=[np.arange(10)]) # series can also be created using a constant, such as (1) or (a), each element containing a using index np.arange()
print(s)

0    a
1    a
2    a
3    a
4    a
5    a
6    a
7    a
8    a
9    a
dtype: object

**Pandas.Concat function** in series as list and in dataFrame

In [ ]:
import pandas as pd
tuesday=pd.Series({'lap1':'1:30','lap2':'1:35','lap3':'1:20','lap4':'1:40'})
wednesday=pd.Series({'lap1':'1:20','lap2':'1:15','lap3':'1:30','lap4':'1:20'})
laps=pd.concat([tuesday,wednesday],keys=['tuesday','wednesday'])
print(laps)

tuesday    lap1    1:30
           lap2    1:35
           lap3    1:20
           lap4    1:40
wednesday  lap1    1:20
           lap2    1:15
           lap3    1:30
           lap4    1:20
dtype: object

In [ ]:
#concat in dataframe .concate()

#creating bunch of sentences

In [ ]:
raw_docs= ["I am writing some very  basic english sentences",
          "I'm just writing it for the demo PURPOSE to make audience understand the basics."
          "The point is to _learn HOW it works_ on #simple # data."]

In [ ]:
#importing nltk package national language toolkit
import nltk

In [ ]:
nltk.download()
#python -m nltk.downloder all

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d)
Command 'd)' unrecognized

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> Download
Command 'Download' unrecognized

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> l
Packages:
  [ ] abc................. Australian Broadcasting Commission 2006
  [ ] alpino.............. Alpino Dutch Treebank
  [ ] averaged_perceptron_tagger Averaged Perceptron Tagger
  [ ] averaged_perceptron_tagger_eng Averaged Perceptron Tagger (JSON)
  [ ] averaged_perceptron_tagger_ru Averaged Perceptron Tagger (Russian)
  [ ] averaged_perceptron_tagger_rus Averaged Perceptron Tagger (Russian)
  [ ] basque_grammars..... Grammars for Basque
  [ ] bcp47............... BCP-47 Language Tags
  [ ] biocreative_ppi..... BioCreAtIvE (Critical Assessment of Information
                           Extraction Systems in Biology)
  [ ] bllip_wsj_no_aux.... BLLIP Parser: WSJ Model
  [ ] book_grammars....... Grammars from NLTK Book
  [ ] brown............... Brown Corpus
  [ ] brown_tei........... Brown Corpus (TEI XML Version)
  [ ] cess_cat............ CESS-CAT Treebank
  [ ] cess_esp............ CESS-ESP Treebank
  [ ] chat80.............. Chat-80 Data Files
  [ ] city_database....... City Database
  [ ] cmudict............. The Carnegie Mellon Pronouncing Dictionary (0.6)
  [ ] comparative_sentences Comparative Sentence Dataset
Hit Enter to continue:
  [ ] comtrans............ ComTrans Corpus Sample
  [ ] conll2000........... CONLL 2000 Chunking Corpus
  [ ] conll2002........... CONLL 2002 Named Entity Recognition Corpus
  [ ] conll2007........... Dependency Treebanks from CoNLL 2007 (Catalan
                           and Basque Subset)
  [ ] crubadan............ Crubadan Corpus
  [ ] dependency_treebank. Dependency Parsed Treebank
  [ ] dolch............... Dolch Word List
  [ ] english_wordnet..... Open English Wordnet
  [ ] europarl_raw........ Sample European Parliament Proceedings Parallel
                           Corpus
  [ ] extended_omw........ Extended Open Multilingual WordNet
  [ ] floresta............ Portuguese Treebank
  [ ] framenet_v15........ FrameNet 1.5
  [ ] framenet_v17........ FrameNet 1.7
  [ ] gazetteers.......... Gazeteer Lists
  [ ] genesis............. Genesis Corpus
  [ ] gutenberg........... Project Gutenberg Selections
  [ ] ieer................ NIST IE-ER DATA SAMPLE
  [ ] inaugural........... C-Span Inaugural Address Corpus
  [ ] indian.............. Indian Language POS-Tagged Corpus
Hit Enter to continue:
  [ ] jeita............... JEITA Public Morphologically Tagged Corpus (in
                           ChaSen format)
  [ ] kimmo............... PC-KIMMO Data Files
  [ ] knbc................ KNB Corpus (Annotated blog corpus)
  [ ] large_grammars...... Large context-free and feature-based grammars
                           for parser comparison
  [ ] lin_thesaurus....... Lin's Dependency Thesaurus
  [ ] mac_morpho.......... MAC-MORPHO: Brazilian Portuguese news text with
                           part-of-speech tags
  [ ] machado............. Machado de Assis -- Obra Completa
  [ ] masc_tagged......... MASC Tagged Corpus
  [ ] maxent_ne_chunker... ACE Named Entity Chunker (Maximum entropy)
  [ ] maxent_ne_chunker_tab ACE Named Entity Chunker (Maximum entropy)
  [ ] maxent_treebank_pos_tagger Treebank Part of Speech Tagger (Maximum entropy)
  [ ] maxent_treebank_pos_tagger_tab Treebank Part of Speech Tagger (Maximum entropy)
  [ ] mock_corpus......... Mock Corpus
  [ ] moses_sample........ Moses Sample Models
  [ ] movie_reviews....... Sentiment Polarity Dataset Version 2.0
  [ ] mte_teip5........... MULTEXT-East 1984 annotated corpus 4.0
  [ ] mwa_ppdb............ The monolingual word aligner (Sultan et al.
                           2015) subset of the Paraphrase Database.
Hit Enter to continue: Identifier
  [ ] names............... Names Corpus, Version 1.3 (1994-03-29)
  [ ] nombank.1.0......... NomBank Corpus 1.0
  [ ] nonbreaking_prefixes Non-Breaking Prefixes (Moses Decoder)
  [ ] nps_chat............ NPS Chat
  [ ] omw-1.4............. Open Multilingual Wordnet
  [ ] omw................. Open Multilingual Wordnet
  [ ] opinion_lexicon..... Opinion Lexicon
  [ ] panlex_swadesh...... PanLex Swadesh Corpora
  [ ] paradigms........... Paradigm Corpus
  [ ] pe08................ Cross-Framework and Cross-Domain Parser
                           Evaluation Shared Task
  [ ] perluniprops........ perluniprops: Index of Unicode Version 7.0.0
                           character properties in Perl
  [ ] pil................. The Patient Information Leaflet (PIL) Corpus
  [ ] pl196x.............. Polish language of the XX century sixties
  [ ] porter_test......... Porter Stemmer Test Files
  [ ] ppattach............ Prepositional Phrase Attachment Corpus
  [ ] problem_reports..... Problem Report Corpus
  [ ] product_reviews_1... Product Reviews (5 Products)
  [ ] product_reviews_2... Product Reviews (9 Products)
  [ ] propbank............ Proposition Bank Corpus 1.0
Hit Enter to continue: i
  [ ] pros_cons........... Pros and Cons
  [ ] ptb................. Penn Treebank
  [ ] punkt............... Punkt Tokenizer Models
  [ ] punkt_tab........... Punkt Tokenizer Models
  [ ] qc.................. Experimental Data for Question Classification
  [ ] reuters............. The Reuters-21578 benchmark corpus, ApteMod
                           version
  [ ] rslp................ RSLP Stemmer (Removedor de Sufixos da Lingua
                           Portuguesa)
  [ ] rte................. PASCAL RTE Challenges 1, 2, and 3
  [ ] sample_grammars..... Sample Grammars
  [ ] semcor.............. SemCor 3.0
  [ ] senseval............ SENSEVAL 2 Corpus: Sense Tagged Text
  [ ] sentence_polarity... Sentence Polarity Dataset v1.0
  [ ] sentiwordnet........ SentiWordNet
  [ ] shakespeare......... Shakespeare XML Corpus Sample
  [ ] sinica_treebank..... Sinica Treebank Corpus Sample
  [ ] smultron............ SMULTRON Corpus Sample
  [ ] snowball_data....... Snowball Data
  [ ] spanish_grammars.... Grammars for Spanish
  [ ] state_union......... C-Span State of the Union Address Corpus
Hit Enter to continue: 1
  [ ] stopwords........... Stopwords Corpus
  [ ] subjectivity........ Subjectivity Dataset v1.0
  [ ] swadesh............. Swadesh Wordlists
  [ ] switchboard......... Switchboard Corpus Sample
  [ ] tagsets............. Help on Tagsets
  [ ] tagsets_json........ Help on Tagsets (JSON)
  [ ] timit............... TIMIT Corpus Sample
  [ ] toolbox............. Toolbox Sample Files
  [ ] treebank............ Penn Treebank Sample
  [ ] twitter_samples..... Twitter Samples
  [ ] udhr2............... Universal Declaration of Human Rights Corpus
                           (Unicode Version)
  [ ] udhr................ Universal Declaration of Human Rights Corpus
  [ ] unicode_samples..... Unicode Samples
  [ ] universal_tagset.... Mappings to the Universal Part-of-Speech Tagset
  [ ] universal_treebanks_v20 Universal Treebanks Version 2.0
  [ ] vader_lexicon....... VADER Sentiment Lexicon
  [ ] verbnet3............ VerbNet Lexicon, Version 3.3
  [ ] verbnet............. VerbNet Lexicon, Version 2.1
  [ ] webtext............. Web Text Corpus
  [ ] wmt15_eval.......... Evaluation data from WMT15
Hit Enter to continue: l
  [ ] word2vec_sample..... Word2Vec Sample
  [ ] wordnet2021......... Open English Wordnet 2021
  [ ] wordnet2022......... Open English Wordnet 2022
  [ ] wordnet31........... Wordnet 3.1
  [ ] wordnet............. WordNet
  [ ] wordnet_ic.......... WordNet-InfoContent
  [ ] words............... Word Lists
  [ ] ycoe................ York-Toronto-Helsinki Parsed Corpus of Old
                           English Prose

Collections:
  [ ] all-corpora......... All the corpora
  [ ] all-nltk............ All packages available on nltk_data gh-pages
                           branch
  [ ] all................. All packages
  [ ] book................ Everything used in the NLTK Book
  [ ] popular............. Popular packages
  [ ] tests............... Packages for running tests
  [ ] third-party......... Third-party data packages

([*] marks installed packages)

Download which package (l=list; x=cancel)?
  Identifier> punkt

    Downloading package punkt to /root/nltk_data...
      Unzipping tokenizers/punkt.zip.

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> stopwords

    Downloading package stopwords to /root/nltk_data...
      Unzipping corpora/stopwords.zip.

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> wordnet

    Downloading package wordnet to /root/nltk_data...

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> averaged_perceptron_tagger

    Downloading package averaged_perceptron_tagger to
        /root/nltk_data...
      Unzipping taggers/averaged_perceptron_tagger.zip.

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> popular

    Downloading collection 'popular'
       |
       | Downloading package cmudict to /root/nltk_data...
       |   Unzipping corpora/cmudict.zip.
       | Downloading package gazetteers to /root/nltk_data...
       |   Unzipping corpora/gazetteers.zip.
       | Downloading package genesis to /root/nltk_data...
       |   Unzipping corpora/genesis.zip.
       | Downloading package gutenberg to /root/nltk_data...
       |   Unzipping corpora/gutenberg.zip.
       | Downloading package inaugural to /root/nltk_data...
       |   Unzipping corpora/inaugural.zip.
       | Downloading package movie_reviews to /root/nltk_data...
       |   Unzipping corpora/movie_reviews.zip.
       | Downloading package names to /root/nltk_data...
       |   Unzipping corpora/names.zip.
       | Downloading package shakespeare to /root/nltk_data...
       |   Unzipping corpora/shakespeare.zip.
       | Downloading package stopwords to /root/nltk_data...
       |   Package stopwords is already up-to-date!
       | Downloading package treebank to /root/nltk_data...
       |   Unzipping corpora/treebank.zip.
       | Downloading package twitter_samples to /root/nltk_data...
       |   Unzipping corpora/twitter_samples.zip.
       | Downloading package omw to /root/nltk_data...
       | Downloading package omw-1.4 to /root/nltk_data...
       | Downloading package wordnet to /root/nltk_data...
       |   Package wordnet is already up-to-date!
       | Downloading package wordnet2021 to /root/nltk_data...
       | Downloading package wordnet31 to /root/nltk_data...
       | Downloading package wordnet_ic to /root/nltk_data...
       |   Unzipping corpora/wordnet_ic.zip.
       | Downloading package words to /root/nltk_data...
       |   Unzipping corpora/words.zip.
       | Downloading package maxent_ne_chunker to /root/nltk_data...
       |   Unzipping chunkers/maxent_ne_chunker.zip.
       | Downloading package punkt to /root/nltk_data...
       |   Package punkt is already up-to-date!
       | Downloading package snowball_data to /root/nltk_data...
       | Downloading package averaged_perceptron_tagger to
       |     /root/nltk_data...
       |   Package averaged_perceptron_tagger is already up-to-date!
       |
     Done downloading collection popular

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q

True

In [ ]:
#convert to lower case
import string

In [ ]:
raw_docs=[doc.lower() for doc in raw_docs]
print(raw_docs)

['i am writing some very  basic english sentences', "i'm just writing it for the demo purpose to make audience understand the basics.the point is to _learn how it works_ on #simple # data."]

raw_docs= ["I am writing some very  basic english sentences",
          "I'm just writing it for the demo PURPOSE to make audience understand the basics."
          "The point is to _learn HOW it works_ on #simple # data."]

**Tokenization**

In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
import nltk
from nltk.tokenize import word_tokenize

word_tokenize("NLTK is finally working")

['NLTK', 'is', 'finally', 'working']

In [ ]:
#word tokenize means breaking your sentence into words and taking your sentences seperated
from nltk.tokenize import word_tokenize
tokenized_docs= [word_tokenize(doc)for doc in raw_docs]
print(raw_docs)

['i am writing some very  basic english sentences', "i'm just writing it for the demo purpose to make audience understand the basics.the point is to _learn how it works_ on #simple # data."]

**Datatypes**

In [ ]:
'''#constant is 200
print(200)
1. Numeric
2. boolean
3. Sequence type
Three categories of data types at high level'''

In [ ]:
# Numeric Data types 1/3
int =3
float=3.5
complex =6+4j

In [ ]:
#Boolean Data type
True
False

In [ ]:
#Sequence Data type
my_string='mystring'
print(len(my_string))
my_string[0:3]
# to concat we use ("var1"+" "+"var2")

8

'mys'

In [ ]:
import pandas as pd
df=pd.read_excel(r"/content/Customer Call List.xlsx")

In [ ]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
df=df.drop_duplicates()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
df=df.drop(columns="Not_Useful_Column")

In [ ]:
df["Last_Name"]=df["Last_Name"].str.lstrip('/')
df["Last_Name"]=df["Last_Name"].str.lstrip('...')
df["Last_Name"]=df["Last_Name"].str.rstrip('_')
#df['Last_Name'].str.strip("_.../")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
df["Phone_Number"]=df["Phone_Number"].str.replace('[^a-zA-Z0-9]','')

In [ ]:
#df["Phone_Number"].apply(lambda x: x[0:3]+'-'+ x[3:6]+'-'+ x[6:10])
#df["Phone_Number"]=df["Phone_Number"].apply(lambda x: str(x))
#str(df['Phone_Number'])
#df["Phone_Number"].apply(lambda x: str(x))
#df["Phone_Number"].apply(lambda x: x[0:3]+ '-' + x[3:6]+ '-' + x[6:10])
df["Phone_Number"] = (
    df["Phone_Number"]
    .astype(str)
    .str.replace(r"\.0$", "", regex=True)
    .str.slice(0,3) + "-" +
    df["Phone_Number"].astype(str).str.slice(3,6) + "-" +
    df["Phone_Number"].astype(str).str.slice(6,10)
)